/**
 * ============================================================================
 * 1. DATABASE SCHEMA STRUCTURE (PostgreSQL - Aligned with your exact SQL Tables)
 * ============================================================================
 * 
 * -- 1. Create Profiles Table (To map your Firebase users)
 * CREATE TABLE profiles (
 *   id TEXT PRIMARY KEY, -- Firebase user.uid stored directly as text
 *   name TEXT,
 *   role TEXT CHECK (role IN ('client', 'professional')),
 *   service_type TEXT, -- null for clients, specific service for professionals
 *   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
 * );
 * 
 * -- 2. Create Bookings Table
 * CREATE TABLE bookings (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   client_id TEXT NOT NULL, -- Ties to the Firebase uid stored directly as text
 *   professional_id TEXT,    -- null until a professional accepts the job
 *   service_type TEXT NOT NULL,
 *   scheduled_date DATE NOT NULL,
 *   scheduled_time TEXT NOT NULL,
 *   notes TEXT,
 *   image_url TEXT,
 *   latitude NUMERIC,
 *   longitude NUMERIC,
 *   status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'completed')),
 *   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
 * );
 */

import { supabase } from "./supabase";

/**
 * ============================================================================
 * 2. BUCKET UPLOAD HELPER (SUPABASE STORAGE)
 * ============================================================================
 * Reads the local device image path from Expo camera, converts it to a binary Blob,
 * uploads it to a Supabase Storage bucket, and extracts the public URL.
 * 
 * @param {string} fileUri - The local URI of the image from camera/gallery.
 * @param {string} userId - The authenticated user's ID.
 * @returns {Promise<string>} Public download URL of the uploaded image file.
 */
const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
const lookup = new Uint8Array(256);
for (let i = 0; i < chars.length; i++) {
  lookup[chars.charCodeAt(i)] = i;
}

function decodeBase64ToArrayBuffer(base64) {
  let bufferLength = base64.length * 0.75;
  let len = base64.length;
  let i;
  let p = 0;
  let encoded1, encoded2, encoded3, encoded4;

  if (base64[base64.length - 1] === "=") {
    bufferLength--;
    if (base64[base64.length - 2] === "=") {
      bufferLength--;
    }
  }

  const arrayBuffer = new ArrayBuffer(bufferLength);
  const bytes = new Uint8Array(arrayBuffer);

  for (i = 0; i < len; i += 4) {
    encoded1 = lookup[base64.charCodeAt(i)];
    encoded2 = lookup[base64.charCodeAt(i + 1)];
    encoded3 = lookup[base64.charCodeAt(i + 2)];
    encoded4 = lookup[base64.charCodeAt(i + 3)];

    bytes[p++] = (encoded1 << 2) | (encoded2 >> 4);
    bytes[p++] = ((encoded2 & 15) << 4) | (encoded3 >> 2);
    bytes[p++] = ((encoded3 & 3) << 6) | (encoded4 & 63);
  }

  return arrayBuffer;
}

export async function uploadBookingImage(fileUri, userId) {
  if (!fileUri || typeof fileUri !== "string") {
    throw new Error("Image file URI must be a valid string for upload.");
  }
  
  try {
    // 1. Convert local URI file into a blob using XMLHttpRequest (XHR) to prevent indefinite hangs in React Native
    const blob = await new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.onload = function () {
        resolve(xhr.response);
      };
      xhr.onerror = function (e) {
        console.error("XHR conversion to blob failed:", e);
        reject(new Error("Failed to convert image URI to blob."));
      };
      xhr.responseType = "blob";
      xhr.open("GET", fileUri, true);
      xhr.send(null);
    });

    // 2. Read the Blob as Base64 using standard FileReader
    const base64Str = await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => {
        const parts = reader.result.split(",");
        resolve(parts[1] || parts[0]);
      };
      reader.onerror = (e) => {
        console.error("FileReader failed:", e);
        reject(new Error("Failed to read image blob as base64."));
      };
      reader.readAsDataURL(blob);
    });

    // 3. Decode base64 to binary ArrayBuffer (safe for React Native fetch)
    const arrayBuffer = decodeBase64ToArrayBuffer(base64Str);
    
    // 4. Extract file extension dynamically
    const fileExt = fileUri.split(".").pop() || "jpg";
    const path = `${userId}/${Date.now()}.${fileExt}`;
    
    // 5. Upload to Supabase bucket 'booking-attachments'
    const { data, error } = await supabase.storage
      .from("booking-attachments")
      .upload(path, arrayBuffer, {
        cacheControl: "3600",
        upsert: false,
        contentType: `image/${fileExt === "png" ? "png" : "jpeg"}`
      });
      
    if (error) throw error;
    
    // 6. Retrieve public URL link
    const { data: publicUrlData } = supabase.storage
      .from("booking-attachments")
      .getPublicUrl(path);
      
    return publicUrlData.publicUrl;
  } catch (error) {
    console.error("Error uploading image to Supabase Storage:", error);
    throw error;
  }
}

/**
 * ============================================================================
 * 3. SUBMIT BOOKING MUTATION
 * ============================================================================
 * Handles the complete booking creation pipeline: uploads images if provided,
 * structures the final database payload, and inserts the record into Supabase.
 * 
 * @param {object} bookingData - Metadata containing service details, slots, notes, and location.
 * @param {string} [fileUri] - Optional local camera device file path.
 * @returns {Promise<object>} The newly inserted database record row object.
 */
export async function createJobRequest(bookingData, fileUri, fileUris = []) {
  const {
    clientId,
    serviceType,
    scheduledDate,
    scheduledTime,
    notes,
    latitude,
    longitude
  } = bookingData;

  // Validate mandatory fields
  if (!clientId) throw new Error("Client ID is required.");
  if (!serviceType) throw new Error("Service Type is required.");
  if (!scheduledDate) throw new Error("Scheduled Date is required.");
  if (!scheduledTime) throw new Error("Scheduled Time is required.");
  if (latitude === undefined || longitude === undefined) {
    throw new Error("Location coordinates (latitude and longitude) are required.");
  }

  try {
    let publicPhotoUrls = [];
    
    // 1. Process image upload if an image path is present
    const uris = Array.isArray(fileUris) && fileUris.length > 0
      ? fileUris.filter((x) => typeof x === "string" && x.trim().length > 0)
      : fileUri
        ? [fileUri]
        : [];

    for (const uri of uris) {
      const uploadedUrl = await uploadBookingImage(uri, clientId);
      if (uploadedUrl) publicPhotoUrls.push(uploadedUrl);
    }
    
    // 2. Prepare payload matching your exact PostgreSQL database columns (no total_estimate)
    const payload = {
      client_id: clientId,
      professional_id: null, // Remains null until accepted by an expert
      service_type: serviceType.toLowerCase().trim(),
      scheduled_date: scheduledDate,
      scheduled_time: scheduledTime,
      notes: notes || "",
      image_url: publicPhotoUrls.length > 0 ? JSON.stringify(publicPhotoUrls) : null,
      latitude,
      longitude,
      status: "pending" // Default system initial state
    };
    
    // 3. Write row into 'bookings' table
    const { data, error } = await supabase
      .from("bookings")
      .insert([payload])
      .select()
      .single();
      
    if (error) throw error;
    return data;
  } catch (error) {
    console.error("Error creating job request in Supabase:", error);
    throw error;
  }
}

/**
 * Fetch a single booking row from API by booking id.
 *
 * @param {number|string} bookingId
 * @returns {Promise<object|null>}
 */
export async function fetchBookingById(bookingId) {
  if (!bookingId) return null;

  const { data, error } = await supabase
    .from("bookings")
    .select("*")
    .eq("id", bookingId)
    .single();

  if (error) throw error;
  return data || null;
}

/**
 * Fetch latest bookings for a client.
 *
 * @param {string} clientId
 * @param {number} limit
 * @returns {Promise<Array>}
 */
export async function fetchClientBookings(clientId, limit = 5) {
  if (!clientId) return [];

  const { data, error } = await supabase
    .from("bookings")
    .select("*")
    .eq("client_id", clientId)
    .order("created_at", { ascending: false })
    .limit(limit);

  if (error) throw error;
  return data || [];
}

/**
 * Write booking lifecycle log into Supabase table `booking_logs`.
 * Expected columns:
 * - id (identity pk)
 * - booking_id (bigint/text)
 * - client_id (text)
 * - action (text)
 * - message (text)
 * - created_at (timestamp default now)
 *
 * @param {object} log
 * @returns {Promise<object|null>}
 */
export async function createBookingLog(log) {
  const payload = {
    booking_id: log?.bookingId,
    client_id: log?.clientId || null,
    action: log?.action || "booking_created",
    message: log?.message || "Booking created",
  };

  const { data, error } = await supabase
    .from("booking_logs")
    .insert([payload])
    .select()
    .single();

  if (error) throw error;
  return data || null;
}

/**
 * Fetch logs for one booking from API (`booking_logs` table).
 *
 * @param {number|string} bookingId
 * @returns {Promise<Array>}
 */
export async function fetchBookingLogsByBookingId(bookingId) {
  if (!bookingId) return [];

  const { data, error } = await supabase
    .from("booking_logs")
    .select("*")
    .eq("booking_id", bookingId)
    .order("created_at", { ascending: false });

  if (error) throw error;
  return data || [];
}

/**
 * ============================================================================
 * 4. REAL-TIME DATA SUBSCRIPTIONS (supabase.channel)
 * ============================================================================
 */

/**
 * Streams active bookings changes associated with a specific Client in real time.
 * Perfect for updating status badges ('pending' -> 'accepted' -> 'completed') live.
 * 
 * @param {string} userId - The client's unique Firebase user.uid stored as TEXT.
 * @param {function} onUpdate - Success callback invoked on database modifications.
 * @returns {object} Cleanup object with unsubscribe callback function.
 */
export function subscribeClientBookingChanges(userId, onUpdate) {
  if (!userId) {
    throw new Error("Client User ID is required to listen for active updates.");
  }

  // Create real-time PostgreSQL broadcast channel targeting bookings for this client
  const channel = supabase
    .channel(`client-bookings-${userId}`)
    .on(
      "postgres_changes",
      {
        event: "*", // Listen for INSERTS, UPDATES, and DELETES
        schema: "public",
        table: "bookings",
        filter: `client_id=eq.${userId}` // Server-side TEXT filtering
      },
      (payload) => {
        onUpdate(payload);
      }
    )
    .subscribe();

  // Return clean handle to unsubscribe on unmount
  return {
    unsubscribe: () => {
      supabase.removeChannel(channel);
    }
  };
}

/**
 * Streams incoming 'pending' bookings matching the Professional's active
 * service category so they can claim it in real time.
 * 
 * @param {string} serviceCategory - Category type matching professional profile.
 * @param {function} onUpdate - Success callback receiving pending job inserts.
 * @returns {object} Cleanup object with unsubscribe callback function.
 */
export function subscribeProfessionalIncomingJobs(serviceCategory, onUpdate) {
  if (!serviceCategory) {
    throw new Error("Service category is required to stream pending requests.");
  }

  const normalizedCategory = serviceCategory.toLowerCase().trim();

  // Listen for newly created pending requests
  const channel = supabase
    .channel(`professional-jobs-${normalizedCategory}`)
    .on(
      "postgres_changes",
      {
        event: "INSERT", // Only listen for new incoming tickets
        schema: "public",
        table: "bookings",
        filter: "status=eq.pending" // Filter pending jobs on server-side
      },
      (payload) => {
        // Double-check category matching locally to ensure exact type-filtering
        if (payload.new && payload.new.service_type === normalizedCategory) {
          onUpdate(payload.new);
        }
      }
    )
    .subscribe();

  // Return unsubscribe cleanup handle
  return {
    unsubscribe: () => {
      supabase.removeChannel(channel);
    }
  };
}

/**
 * Notification center helpers.
 * Table expected: notification_events
 * Columns:
 * - id (identity)
 * - recipient_id (text)
 * - event_type (text)
 * - title (text)
 * - body (text)
 * - booking_id (bigint, nullable)
 * - created_at (timestamptz default now())
 */
export async function createNotificationEvent({
  recipientId,
  eventType = "system",
  title,
  body = "",
  bookingId = null,
}) {
  if (!recipientId || !title) return null;

  const payload = {
    recipient_id: recipientId,
    event_type: eventType,
    title,
    body,
    booking_id: bookingId,
  };

  const { data, error } = await supabase
    .from("notification_events")
    .insert([payload])
    .select()
    .single();

  if (error) throw error;
  return data || null;
}

export async function fetchNotificationEvents(recipientId) {
  if (!recipientId) return [];
  const { data, error } = await supabase
    .from("notification_events")
    .select("*")
    .eq("recipient_id", recipientId)
    .order("created_at", { ascending: false });

  if (error) throw error;
  return data || [];
}

export async function deleteNotificationEvent(id) {
  if (!id) return;
  const { error } = await supabase
    .from("notification_events")
    .delete()
    .eq("id", id);
  if (error) throw error;
}

export async function clearNotificationEvents(recipientId) {
  if (!recipientId) return;
  const { error } = await supabase
    .from("notification_events")
    .delete()
    .eq("recipient_id", recipientId);
  if (error) throw error;
}
